# From https://github.com/urbantrout/craftcms/blob/5fb038ff50b7b27a269b5b842fda8b7c98d3232e/README.md
version: '2.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 17010:80
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # nginx configuration
      - ./assets:/var/www/html/web/assets # For static assets (media, js and css)

  craft:
    image: urbantrout/craftcms:mysql # Use mysql instead of postgresql
    depends_on:
      - mariadb
    volumes:
      - ./assets:/var/www/html/web/assets:z
      - ./backups:/var/www/html/storage/backups # Used for db restore on start
      - ./templates:/var/www/html/templates # Craft CMS template files
      - ./translations:/var/www/html/translations
      - ./redactor:/var/www/html/config/redactor
    environment:
      DEPENDENCIES: >- # additional composer packages
        yiisoft/yii2-redis
        craftcms/redactor
        spicyweb/craft-neo
        nystudio107/craft-imageoptimize
        verbb/field-manager

      CRAFTCMS_EMAIL: admin@company.com
      CRAFTCMS_USERNAME: admin
      CRAFTCMS_PASSWORD: password
      CRAFTCMS_SITENAME: Cigarette Racing
      CRAFTCMS_SITEURL: http://cigaretteracing.local

      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      DB_DSN: mysql:host=mariadb;dbname=craft
      DB_SERVER: mariadb
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: mysql
      DB_PORT: 3306
      DB_TABLE_PREFIX: ut

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 17013:80
    volumes:
      - /sessions
    links:
      - mariadb:db

  mariadb:
    image: mariadb:10.1
    ports:
      - 17011:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    volumes:
      # Persistent data
      - dbdata:/var/lib/mysql

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
